### ISSUE TITLE
Вопрос.

### ISSUE THREAD

**Issue by MerdedSpade** [ekonda/kutana#27]
Kак получить ID пользователя написавшего сообщение?

**Comment by Metamorfozer** [comment]
`print(message.from_id)`

**Comment by michaelkrukov** [comment]
Пожалуйста, старайтесь использовать issues для конструктивных предложений, описания ошибок и т.д. Для вопросов лучше 1) перечитать документацию 2) использовать вконтакте.

В ближайшее время, если будет необходимость, будет создано место для централизованных обсуждений. Сейчас есть группа во вконтакте.
