### ISSUE TITLE
Support for signals is not available on Windows

### ISSUE THREAD

**Issue by daeeros** [ekonda/kutana#49]
## Expected Behavior

App need to start.
## Actual Behavior

App shooting down with NotImplementedError in add_signal_handler (file > kutana.py > line(203) > (add_signal_handler)
## Possible Solution
Make the correct exception handler in the event loop.

## Steps to Reproduce (for bugs)

1. Install all requirements
2. Try to run runer.py
3. We geting the NotImplementedError in add_signal_handler (file > kutana.py > line(203) > (add_signal_handler) will Windows no't support signals.

## Your Environment

* Python vesion:  3.6
* Kutana version: 4.1.3
* Platform: Windows 10 x64 (1809)
* Country: Turkey

**Comment by michaelkrukov** [comment]
Feel free to open, if any issues remains
