### ISSUE TITLE
How to change prefix?

### ISSUE THREAD

**Issue by nukdokplex** [ekonda/kutana#50]
I'd not found any solutions to change bot prefix. Is it possible?

**Comment by DexLM01** [comment]
Yes it is possible you should go along the path kutana / kutana.py on line 37 there is a setting for these prefixes

**Comment by DexLM01** [comment]
If my message helped you, please kindly close the issue.

**Comment by michaelkrukov** [comment]
Actually, you better off settings prefix in your application code without touching the library.

```py
app = Kutana(...)
app.config['prefixes'] = ('hey', 'bot')
```
