### ISSUE TITLE
Bot commands with  alias

### ISSUE THREAD

**Issue by sasha00123** [ekonda/kutana#55]
Commands like /command@BotUsername don't work as expected.

Example code:
```
@plugin.on_commands(commands=["command"])
async def _(msg, ctx):
    await ctx.reply("Works!!!")

@plugin.on_any_unprocessed_message()
async def _(msg, ctx):
    await ctx.reply("Doesn't work :-(")
```

## Expected Behavior

/command => Works!!!
/command@BotUsername => Works!!!

## Actual Behavior

/command => Works!!!
/command@BotUsername => Doesn't work :-(

## Possible Solution

Strip anything after @ in commands.

## Steps to Reproduce (for bugs)

1. Run example code
2. Write to a bot
3. Cry

## Context

This feature is quite useful if there're multiple bots in one chat.

## Your Environment

* Python vesion: 3.8.5
* Kutana version: 4.2.0
* Platform: Arch Linux 5.7.11-arch1-1
* Country: Russia

**Comment by michaelkrukov** [comment]
Без пробелов вконтакте не рассматривает сообщение '/command@BotUsername' как текст с упоминанием. Поэтому бот и не может вырезать это. Потому что это действительно не упоминание. Некоторые команды могут содержать упоминания других пользователей, поэтому вырезать всё после '@' - плохой вариант, да и бот может работать с командами и аргументами, которые содержат символ '@'. 

Для телеграмма этот функционал не реализован, хотя было бы неплохо. Но и там ситуация с упоминания будет аналогичная. 

Не похоже, чтобы в поведении, приведённым в пример, было что-то не так. Всё правильно. Особенно это понятно из-за того, что если бот получает только сообщения с упоминаниями, он не будет получать сообщения из примера. Да и вроде случайно такое написать не получится - чтобы появился список с вариантами упоминания, надо ставить проблема (для мобильных клиентов и браузера)

**Comment by sasha00123** [comment]
В Telegram бот даже при включенном Group Privacy получает уведомления о команде ему. В других библиотеках, которые я использовал, данная фича работает корректно.

Во ВКонтакте это может быть полезно если нескольким ботам в беседе открыт доступ ко всем сообщениям.

**Comment by michaelkrukov** [comment]
Есть примеры?

**Comment by sasha00123** [comment]
Соглашусь, в ВК такой функционал не особо удобен.

А вот в Telegram, когда несколько ботов с одинаковыми командами, он автоматически предлагает использовать подобный синтаксис.
![Test](https://i.ibb.co/3mDkzTZ/Screenshot-20200806-172228.png)

**Comment by michaelkrukov** [comment]
Действительно. Когда буду добавлять функционал с вырезанием упоминания в телеграмм - учту этот момент.
