### ISSUE TITLE
Возможность добавлять описание аттачей при их загрузке (Telegram)

### ISSUE THREAD

**Issue by daeeros** [ekonda/kutana#66]
При выводе изображения иногда нужно и написать кое-что, но телеграм отправляет это отдельным сообщением, было бы гораздо удобнее если бы при загрузке аттачей была бы возможность указывать их описание - caption

К примеру:

```
from kutana import Attachment

with open("assets/pizza.png", "rb") as f:
    image = Attachment.new(f.read(), caption="А вот и твоя пицца!")
```

Это было бы очень удобно :3

**Comment by michaelkryukov** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13236694/164987727-5161487a-bf56-41fa-8453-dbde148bebc6.png">

```
with open(get_path(__file__, "assets/pizza.png"), "rb") as fh:
        image = Attachment.new(fh.read(), "pizza.png", title="Pizza")

    await ctx.reply(t("Image"), attachments=image)
```

**Comment by michaelkryukov** [comment]
https://github.com/ekonda/kutana/commit/d611358940d4574e83bd5177489fe3dadc030a52#diff-0f6b22100d65f4ff88c780b3cf6fae6650364f82649f6d0b8d3dfa33e299e12dR11

Реализовал поддержку "title" для телеграмма. Вроде должно решить вопрос)
