### ISSUE TITLE
Переписать клиентский код с aiohttp на httpx

### ISSUE THREAD

**Issue by michaelkryukov** [ekonda/kutana#71]
Библиотека `httpx` более адекватно реализована, и в целом лучше, чем `aiohttp`. Одно из критичных мест – загрузка документов в телеграмм. `httpx` лучше работает с мультипартами.

**Comment by daeeros** [comment]
> Библиотека `httpx` более адекватно реализована, и в целом лучше, чем `aiohttp`. Одно из критичных мест – загрузка документов в телеграмм. `httpx` лучше работает с мультипартами.

Если честно, это кажется плохой идеей, я всё таки решил протестировать обе библиотеки под нагрузкой, как выяснилось, aiohttp почти в 10 раз быстрее выполнил все запросы нежели httpx,  а с учётом текущих задач, как раз таки скорость большого кол-ва запросов и трубется.
![image](https://user-images.githubusercontent.com/34482855/210372219-6844e1ea-5d83-43c9-9e38-3033d2a24bf3.png)

**Comment by michaelkryukov** [comment]
На практике, ничего не стало работать в 10 раз медленнее, код стал покомфортнее. Критика/проблемы с производительностью принимаются в отдельных ищусах.
